name: tao vlan
  hosts: all
  gather_facts: no

  tasks:
    - name: Create loopback
      ios_13_interface:
        name: loopback {{ item.number }}
        ipv4: 10.0.{{ item.number }}.1/24
        state: present
      with_items:
        - { number: 1}
        - { number: 2}
        - { number: 3}

    - name: Show ip 
      ios_command:
        commands:
          - show ip int br
      register: show_vlan

    - debug: var=show_vlan.stdout_lines
